## Pytorch Fundamentals

In [1]:
##import libraries
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Tensor Basics
### Creating Tensor
Documentation link : https://pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # no dimensions

0

In [4]:
#if need the value of the tensor use .item()
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([3,3])
print(vector)
print(vector.ndim)           #means pairs of square bracket
print(vector.shape)          #no of elements in the square bracket

tensor([3, 3])
1
torch.Size([2])


In [6]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [10,12]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [10, 12]])
2
torch.Size([2, 2])


In [7]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [8]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
#more code to undestand the tensor
#scalar and vector lower case
#matrix and tensor upper case
'''
My understanding of shape: 0th dim: matrix (all elements)
                         : 1st dim: no of rows
                         : 2nd dim: no of elements in single row
'''
T = torch.tensor([[[1,2,3,4],
                   [5,6,7,8],
                   [6,7,8,9]]])

print(T)
print(T.ndim)
print(T.shape)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [6, 7, 8, 9]]])
3
torch.Size([1, 3, 4])


## Random Tensors
*   #### random tensors are important because the many neural network weights start with the random values, we will adjust those random values to better learn the model
*   #### `start with random number --> look at data --> update random no --> look at data --> update`
*   #### `documentation:` https://pytorch.org/docs/stable/generated/torch.rand.html

In [10]:
#creating random tensor
random_tensor = torch.rand(1,3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.6584, 0.6614, 0.9196, 0.1498],
         [0.0581, 0.6132, 0.2614, 0.3817],
         [0.0740, 0.0369, 0.0425, 0.7068]]])
3
torch.Size([1, 3, 4])


In [11]:
#creating a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size= (64,64,3)) #height x width x channels
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([64, 64, 3]), 3)

In [12]:
random_image_tensor[:,:,0].shape

torch.Size([64, 64])

## Zeros and Ones Tensors

In [13]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
ones = torch.ones((3,4))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


## Range of Tensors and Tensor-like

In [15]:
# use torch.range
U = torch.arange(0,11)

In [16]:
#tensor_like : if want to create other tensors who has same shape as above tensor
ten_zeros = torch.zeros_like(U)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
*  dtype
*  device
*  `documentation`: https://pytorch.org/docs/stable/tensors.html

### Note: major 3 types of errors while working with Pytorch
*  Tensor not right datatype : if cal is performed btw for eg: float16 and float 32
*  Tensor not right shape
*  Tensor not on right device : suppose one tensor is on cpu and one is on gpu

In [17]:
#float32 tensor--> eventough dtype=None, still default value of dtype is float32: single precision floating point no
float32_tensor = torch.tensor([4.0,5,6], dtype=None,
                                         device=None,          # default is cpu, can also change into cuda
                                         requires_grad=False)  # this comes in picture during parameters optimization

print(float32_tensor)
print(float32_tensor.dtype)

tensor([4., 5., 6.])
torch.float32


### convert the datatype

In [18]:
#convert the datatype from one form into another
float_16_tensor = float32_tensor.type(torch.half)
float_16_tensor

tensor([4., 5., 6.], dtype=torch.float16)

In [19]:
## as per me it should throw an error ?
## thing is some operation throw error
float32_tensor*float_16_tensor

tensor([16., 25., 36.])

In [20]:
# find out the details of the some tensor, which will help to debug the code
some_tensor = torch.rand(3,4)
print(f"Datatype of tensor is: {some_tensor.dtype}")
print(f"Shape of the tensor is: {some_tensor.shape}")
print(f"Device of which tensor is present: {some_tensor.device}")

Datatype of tensor is: torch.float32
Shape of the tensor is: torch.Size([3, 4])
Device of which tensor is present: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* **Addition**
* **Substraction**
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [21]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10     # element wise addition

tensor([11, 12, 13])

In [22]:
#multiply the tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [23]:
#Pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [24]:
#matrix multiplication - elementwise
T1 = torch.tensor([1,2,3])
element_wise = T1*T1
print(element_wise)

tensor([1, 4, 9])


In [25]:
# matrix multiplication - dot
# `inner dimensions must match`
# @ can alos be used
dot = torch.matmul(T1,T1)
print(dot)

tensor(14)


In [26]:
# use of transpose
T1 = torch.tensor([[1,2],
                   [3,4],
                   [5,6]])

T2 = torch.tensor([[7,8],
                   [9,10],
                   [11,12]])

In [27]:
dot = torch.matmul(T1, T2.T)
print(dot)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


## Tensor aggregation
* min
* max
* mean
* sum

In [28]:
# create a tensor
t = torch.arange(0,100,10)
print(t.dtype)
print(torch.min(t))
print(torch.max(t))
print(torch.mean(t))            #why error pop up ??
'''
answer for this is input tensor data type is long (int64), but
torch.mean does not operate on long datatype
'''

torch.int64
tensor(0)
tensor(90)


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [29]:
# solution
mean_value = torch.mean(t.type(torch.float32))
mean_value

tensor(45.)

## Positonal min and max
* **argmin()** - returns the index of min value in the tensor
* **argmax()** - returns the index of max value in the tensor

In [30]:
t

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
# min value index --> to get value use .item()
t.argmin()

tensor(0)

In [32]:
# max value index --> to get value use.item()
t.argmax()

tensor(9)

## Reshaping, stacking, squeezing, unsqueezing tensors
* **reshaping** : reshape an input tensor to desired shape
* **view** : return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **stacking** : combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **squeeze** : remove all `1` dimensions from a tensor
* **unsqueeze** : add a `1` dimensions to a target tensor at target dimension position
* **permute** : return a view of the input with dimensions permuted (swapped) in a certain way

In [33]:
t = torch.arange(1., 10.)
t, t.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### Reshape

In [34]:
# reshape the tensor
t_reshape = t.reshape(3,3)
print(t_reshape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


## View 
**in this tensors share the same memory, means if you change t_view, t also changes**

In [35]:
# change the view
t_view = t.view(3,3)
print(t_view)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [36]:
t_view[1,1] = 100

In [37]:
t_view

tensor([[  1.,   2.,   3.],
        [  4., 100.,   6.],
        [  7.,   8.,   9.]])

In [38]:
t

tensor([  1.,   2.,   3.,   4., 100.,   6.,   7.,   8.,   9.])

## Stack 

In [39]:
# stack tensors on top of each other
t_stack = torch.stack([t,t,t,t])     # default dim of stack is 0: stack row wise
print(t_stack.shape)

torch.Size([4, 9])


In [40]:
th_stack = torch.stack([t,t,t,t], dim=1) # stacking column wise
print(th_stack.shape)

torch.Size([9, 4])


## Squeeze
* **remove all the `1` dimensions from the input tensors**

In [41]:
t_reshape = t.reshape((1,1,1,1,3,3))
print(t_reshape.shape)

torch.Size([1, 1, 1, 1, 3, 3])


In [42]:
t_squeeze = t_reshape.squeeze()
t_squeeze.shape

torch.Size([3, 3])

## Unsqueeze

In [43]:
t.shape

torch.Size([9])

In [44]:
t_unsqueeze = t.unsqueeze(dim=1)
print(t_unsqueeze.shape)
t_unsqueeze.unsqueeze_(dim=2)         # inplace update _
print(t_unsqueeze.shape)

torch.Size([9, 1])
torch.Size([9, 1, 1])


## Permute
**uses the view, hence change done in permuted tensor will reflect in the original tensor as well**

In [45]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x = torch.rand((64,64,3)) # height, width, channels
x.shape

torch.Size([64, 64, 3])

In [46]:
# permute the original tensors dimensions
x_permute = x.permute(2,0,1)
x_permute.shape

torch.Size([3, 64, 64])

In [47]:
x_permute[0,0,0] = 100000

## Indexing (selecting data from tensors)

In [48]:
t = torch.arange(1,10).reshape(1,3,3)
t.shape

torch.Size([1, 3, 3])

In [49]:
t[0] # index on 0th dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
t[0][0] # index on the 1st dim

tensor([1, 2, 3])

In [51]:
t[0][0][0] # index on the 2nd dim

tensor(1)

In [52]:
t[:,:,1]  # gives column as output

tensor([[2, 5, 8]])

## Pytorch tensors and Numpy
*  Data in NumPy, want in PyTorch tensor --> `torch.from_numpy(ndarray)`
* PyTorch tensor --> Numpy --> `torch.Tensor.numpy()`

In [53]:
# numPy to Tensor
import numpy as np

a = np.arange(1.,8)           # default dtype = float64
tensor = torch.from_numpy(a)  # default dtype = torch.float32
print(a)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [54]:
# how to change default dtype of tensor that it got from numpy
tensor_32 = torch.from_numpy(a).type(torch.float32)
tensor_32.dtype

torch.float32

### What happen if we change the value of the array ?
* `nothing happens`

In [55]:
a = a + 1
a

array([2., 3., 4., 5., 6., 7., 8.])

In [56]:
tensor_32

tensor([1., 2., 3., 4., 5., 6., 7.])

## Tensor to Numpy

In [57]:
tensor = torch.ones(7)             #default = torch.float32
numpy_from_tensor = tensor.numpy()
print(numpy_from_tensor.dtype)

float32


### what happen if we change the Tensor ?
* `nothing change`

In [58]:
tensor  = tensor + 10
tensor

tensor([11., 11., 11., 11., 11., 11., 11.])

In [59]:
numpy_from_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

## Reproducability (trying to take random out of random)

* To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**
* `documentation`: https://pytorch.org/docs/stable/notes/randomness.html

In [60]:
# create two random tensors
T1 = torch.rand(3,4)
T2 = torch.rand(3,4)

print(T1 == T2)   # means both tensors are completely different

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
# random tensor but reproducable
# set the random seed  --- > in case of pytorch torch.manual_seed only work for the single tensor
torch.manual_seed(42)
T3 = torch.rand(3,4)

torch.manual_seed(42)
T4 = torch.rand(3,4)

print(T3)
print(T4)
print(T3 == T4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch objects on the GPUs (faster computations)
* `best-practices`: https://pytorch.org/docs/stable/notes/cuda.html#best-practices
*  This documentation is good when writing the python script to use gpu with argparser

In [62]:
# to check if gpu is available
torch.cuda.is_available()

True

In [63]:
!nvidia-smi

Sat Oct  1 18:22:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.78       Driver Version: 512.78       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P8     4W /  N/A |    316MiB /  4096MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [64]:
# setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
# count the no of GPUs
torch.cuda.device_count()

1

###  Put tensors and models on the GPU

In [66]:
# create a tensor (default device = cpu)
T = torch.Tensor([1.0,2,3])
print(T)
print(T.device)

tensor([1., 2., 3.])
cpu


In [67]:
# move tensor to gpu (if available)
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([11., 11., 11., 11., 11., 11., 11.], device='cuda:0')

## Moving back to the CPU
*   **If tensor is on GPU, can't transform it to NumPy**

In [68]:
# converting tensor_gpu to numpy --> will give error
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# fix to this is 
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu