## Tensor Basics


In [1]:
import torch

In [2]:
#create an empty tensor-> returns a tensor filled with uninitialized data\
x = torch.empty(3)
print(x)

tensor([-1.6248e-14,  3.0893e-41, -3.1552e-15])


In [3]:
#create tensor with random values
y = torch.rand(2,2)
print(y)

tensor([[0.1312, 0.5625],
        [0.5209, 0.7235]])


In [4]:
#create a tensor with specific datatypes
print('default dtype: ',y.dtype)
y = torch.rand((2,2),dtype=torch.float16)
print('changed dtype: ',y.dtype)

default dtype:  torch.float32
changed dtype:  torch.float16


In [5]:
#look at the size of the tensor, since it is function, use()
print(y.size())

torch.Size([2, 2])


In [6]:
#create tensor from data-> ex python list
x = torch.tensor([1.7, 4, 6, 8.9])
print(x)

tensor([1.7000, 4.0000, 6.0000, 8.9000])


## Basic operation on Tensors
    * torch.add_
    * torch.sub_
    * torch.div_
    * torch.mul_

In [7]:
x = torch.rand((2,2))
y = torch.rand((2,2))

#add x and y
z = torch.add(x,y)
print('x: ',x)
print('y: ',y)
print('z: ',z)

x:  tensor([[0.7979, 0.8564],
        [0.8841, 0.9670]])
y:  tensor([[0.1045, 0.9670],
        [0.9743, 0.0599]])
z:  tensor([[0.9023, 1.8234],
        [1.8584, 1.0269]])


In [8]:
#inplace addition --> _function do the inplace update
print('initial y: ',y)
y.add_(x)

print('y after x addition: ',y)

initial y:  tensor([[0.1045, 0.9670],
        [0.9743, 0.0599]])
y after x addition:  tensor([[0.9023, 1.8234],
        [1.8584, 1.0269]])


## How to extract value of single element of torch tensor

In [9]:
x = torch.rand(5,3)
print(x)

tensor([[0.8612, 0.3016, 0.3251],
        [0.1772, 0.2668, 0.4793],
        [0.8520, 0.0654, 0.6757],
        [0.4053, 0.8343, 0.6477],
        [0.9940, 0.4332, 0.3009]])


In [10]:
ele1 = x[1,1]
print(ele1)

#value of the tensor element
ele1_val = x[1,1].item()
print(ele1_val)

tensor(0.2668)
0.2667570114135742


## Resize the tensor
    * .view()

In [11]:
y = x.view(-1,5)
print(y.shape)

torch.Size([3, 5])


# from numpy to tensor or vice -versa
    *  **if using cpu**, means tensor is on cpu, then both tensor and numpy object shares same memory location
    
    """
    ### if suppose gpu is available ###
    
    if torch.cuda.is_available():
        device = torch.device("cuda")
        x = torch.ones(5, device = device)   # method 1
        
        y = torch.ones(5)                    # method 2
        y = y.to(device)                     # this will move the y on device i.e cuda (gpu)
        
        z = x + y                            # this will perform at GPU
        
        ### give an error ###                # bcz gpu tensor cannot convert back into numpy
        z.numpy()    
        
        ### solution --> first convert into cpu tensor ##
        z = z.to("cpu")      
    """

In [12]:
import numpy as np
print('--Tensor to numpy conversion--')
x = torch.ones(5)
print(x)

#conversion from tensor into numpy--> only possible if tensor is on cpu, if tensor is on gpu it will give error
y = x.numpy()
print(y)

#share same memory location
print('-------')
x.add_(1)
print(x)
print(y)


--Tensor to numpy conversion--
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
-------
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## required grads ??
    * lot of time when tensor is created we pass the argumnet requires_grad = True(default= False)
    * reason: variable that we want to optimize, means who gradient will be req in future to update its values. 

In [13]:
#want to optimize the value of weights
w = torch.ones(5, requires_grad= True)
print(w)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
